/**
 * 匯出相關錯誤代碼
 *
 * 涵蓋匯出操作、進度追蹤、匯出通知、匯出偏好設定等場景。
 */
const ExportCodes = {
  EXPORT_OPERATION_FAILED: 'EXPORT_OPERATION_FAILED',
  EXPORT_FAILED: 'EXPORT_FAILED',
  EXPORT_CSV_FAILED: 'EXPORT_CSV_FAILED',
  EXPORT_CSV_SIMULATION_FAILED: 'EXPORT_CSV_SIMULATION_FAILED',
  EXPORT_DOWNLOAD_FAILED: 'EXPORT_DOWNLOAD_FAILED',
  EXPORT_DOWNLOAD_CONFIRMATION_ERROR: 'EXPORT_DOWNLOAD_CONFIRMATION_ERROR',
  EXPORT_URL_CREATION_FAILED: 'EXPORT_URL_CREATION_FAILED',
  EXPORT_MANAGER_INIT_FAILED: 'EXPORT_MANAGER_INIT_FAILED',
  EXPORT_BATCH_PARTIAL_FAILURE: 'EXPORT_BATCH_PARTIAL_FAILURE',
  EXPORT_TEMPORARY_FAILURE: 'EXPORT_TEMPORARY_FAILURE',
  EXPORT_LOCALIZATION_ERROR: 'EXPORT_LOCALIZATION_ERROR',
  EXPORT_LANGUAGE_SET_ERROR: 'EXPORT_LANGUAGE_SET_ERROR',
  EXPORT_DATETIME_FORMAT_ERROR: 'EXPORT_DATETIME_FORMAT_ERROR',
  EXPORT_ERROR_HUMANIZATION_ERROR: 'EXPORT_ERROR_HUMANIZATION_ERROR',
  EXPORT_BENCHMARK_COMPARISON_ERROR: 'EXPORT_BENCHMARK_COMPARISON_ERROR',
  EXPORT_USER_PREFERENCES_SAVE_ERROR: 'EXPORT_USER_PREFERENCES_SAVE_ERROR',
  EXPORT_USER_PREFERENCES_LOAD_ERROR: 'EXPORT_USER_PREFERENCES_LOAD_ERROR',
  EXPORT_USER_FEEDBACK_INIT_ERROR: 'EXPORT_USER_FEEDBACK_INIT_ERROR',
  EXPORT_PREFERENCES_VALIDATION_ERROR: 'EXPORT_PREFERENCES_VALIDATION_ERROR',
  EXPORT_PREFERENCES_RESET_ERROR: 'EXPORT_PREFERENCES_RESET_ERROR',
  EXPORT_PREFERENCES_MERGE_ERROR: 'EXPORT_PREFERENCES_MERGE_ERROR',
  EXPORT_STATISTICS_RANGE_ERROR: 'EXPORT_STATISTICS_RANGE_ERROR',
  EXPORT_STATISTICS_QUERY_ERROR: 'EXPORT_STATISTICS_QUERY_ERROR',
  EXPORT_HISTORY_SEARCH_ERROR: 'EXPORT_HISTORY_SEARCH_ERROR',
  EXPORT_HISTORY_QUERY_ERROR: 'EXPORT_HISTORY_QUERY_ERROR',
  EXPORT_HISTORY_EXPORT_ERROR: 'EXPORT_HISTORY_EXPORT_ERROR',
  EXPORT_PROGRESS_UPDATE_ERROR: 'EXPORT_PROGRESS_UPDATE_ERROR',
  EXPORT_PROGRESS_TRACKING_START_ERROR: 'EXPORT_PROGRESS_TRACKING_START_ERROR',
  EXPORT_PROGRESS_TRACKING_COMPLETE_ERROR: 'EXPORT_PROGRESS_TRACKING_COMPLETE_ERROR',
  EXPORT_PROGRESS_TRACKING_CANCEL_ERROR: 'EXPORT_PROGRESS_TRACKING_CANCEL_ERROR',
  EXPORT_PROGRESS_STATS_ERROR: 'EXPORT_PROGRESS_STATS_ERROR',
  EXPORT_PROGRESS_QUERY_ERROR: 'EXPORT_PROGRESS_QUERY_ERROR',
  EXPORT_PROGRESS_NOTIFIER_INIT_ERROR: 'EXPORT_PROGRESS_NOTIFIER_INIT_ERROR',
  EXPORT_PROGRESS_HISTORY_ERROR: 'EXPORT_PROGRESS_HISTORY_ERROR',
  EXPORT_PROGRESS_CLEANUP_ERROR: 'EXPORT_PROGRESS_CLEANUP_ERROR',
  EXPORT_PROGRESS_CALLBACK_REGISTRATION_ERROR: 'EXPORT_PROGRESS_CALLBACK_REGISTRATION_ERROR',
  EXPORT_NOTIFICATION_START_ERROR: 'EXPORT_NOTIFICATION_START_ERROR',
  EXPORT_NOTIFICATION_GROUP_ERROR: 'EXPORT_NOTIFICATION_GROUP_ERROR',
  EXPORT_NOTIFICATION_ERROR_ALERT: 'EXPORT_NOTIFICATION_ERROR_ALERT',
  EXPORT_NOTIFICATION_COMPLETE_ERROR: 'EXPORT_NOTIFICATION_COMPLETE_ERROR',
  EXPORT_NOTIFICATION_CLEANUP_ERROR: 'EXPORT_NOTIFICATION_CLEANUP_ERROR',
  EXPORT_NOTIFICATION_ADD_ERROR: 'EXPORT_NOTIFICATION_ADD_ERROR'
}

Object.freeze(ExportCodes)

module.exports = { ExportCodes }
