/**
 * 網路相關錯誤代碼
 *
 * 涵蓋網路連線、逾時、DNS、臨時性網路故障等場景。
 */
const NetworkCodes = {
  NETWORK_ERROR: 'NETWORK_ERROR',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  NETWORK_REQUEST_FAILED: 'NETWORK_REQUEST_FAILED',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  NETWORK_INTERRUPTION: 'NETWORK_INTERRUPTION',
  NETWORK_DISCONNECTED: 'NETWORK_DISCONNECTED',
  TEMPORARY_NETWORK_FAILURE: 'TEMPORARY_NETWORK_FAILURE',
  TEMPORARY_FAILURE: 'TEMPORARY_FAILURE',
  DNS_ERROR: 'DNS_ERROR',
  ENOTFOUND_ERROR: 'ENOTFOUND_ERROR',
  UNKNOWN_NETWORK_ERROR: 'UNKNOWN_NETWORK_ERROR'
}

Object.freeze(NetworkCodes)

module.exports = { NetworkCodes }
