/**
 * 安全與權限相關錯誤代碼
 *
 * 涵蓋權限控制、CSP 違規、程式碼注入風險、認證失敗等場景。
 */
const SecurityCodes = {
  PERMISSION_ERROR: 'PERMISSION_ERROR',
  SECURITY_ERROR: 'SECURITY_ERROR',
  CSP_VIOLATION: 'CSP_VIOLATION',
  CODE_INJECTION_RISK: 'CODE_INJECTION_RISK',
  UNSAFE_CSP_EVAL: 'UNSAFE_CSP_EVAL',
  UNSAFE_CSP_INLINE: 'UNSAFE_CSP_INLINE',
  PRIVACY_UNDECLARED_DATA_COLLECTION: 'PRIVACY_UNDECLARED_DATA_COLLECTION',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED'
}

Object.freeze(SecurityCodes)

module.exports = { SecurityCodes }
