/**
 * 儲存與記憶體相關錯誤代碼
 *
 * 涵蓋儲存操作、配額超限、記憶體不足等場景。
 */
const StorageCodes = {
  STORAGE_ERROR: 'STORAGE_ERROR',
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
  STORAGE_ADAPTER_FAILED: 'STORAGE_ADAPTER_FAILED',
  STORAGE_OPERATION_FAILED: 'STORAGE_OPERATION_FAILED',
  STORAGE_LOCAL_ERROR: 'STORAGE_LOCAL_ERROR',
  STORAGE_CORRUPTION_DETECTED: 'STORAGE_CORRUPTION_DETECTED',
  QUOTA_EXCEEDED_ERROR: 'QUOTA_EXCEEDED_ERROR',
  // 語義重疊：三者描述同一概念，歷史遺留
  // 建議未來版本統一為 OUT_OF_MEMORY_ERROR
  OUT_OF_MEMORY_ERROR: 'OUT_OF_MEMORY_ERROR',
  OUT_OF_MEMORY: 'OUT_OF_MEMORY',
  MEMORY_ERROR: 'MEMORY_ERROR',
  MEMORY_DETECTOR_ERROR: 'MEMORY_DETECTOR_ERROR'
}

Object.freeze(StorageCodes)

module.exports = { StorageCodes }
