/**
 * 系統與操作相關錯誤代碼
 *
 * 涵蓋系統操作、初始化、設定、效能、資源、並行控制、
 * 重試機制、Handler/Adapter、健康檢查、錯誤模擬等場景。
 */
const SystemCodes = {
  // 語義重疊：OPERATION_ERROR vs OPERATION_FAILED
  // 歷史遺留，建議未來版本統一
  OPERATION_ERROR: 'OPERATION_ERROR',
  OPERATION_FAILED: 'OPERATION_FAILED',
  UNSUPPORTED_OPERATION: 'UNSUPPORTED_OPERATION',

  // 設定
  CONFIG_ERROR: 'CONFIG_ERROR',

  // 效能
  PERFORMANCE_ERROR: 'PERFORMANCE_ERROR',
  PERFORMANCE_MEMORY_TOO_HIGH: 'PERFORMANCE_MEMORY_TOO_HIGH',
  PERFORMANCE_STARTUP_TOO_SLOW: 'PERFORMANCE_STARTUP_TOO_SLOW',

  // 資源
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_NOT_AVAILABLE: 'RESOURCE_NOT_AVAILABLE',
  RESOURCE_EXHAUSTED: 'RESOURCE_EXHAUSTED',
  MISSING_REQUIRED_DATA: 'MISSING_REQUIRED_DATA',

  // 系統核心
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  INITIALIZATION_ERROR: 'INITIALIZATION_ERROR',
  SERVICE_INITIALIZATION_ERROR: 'SERVICE_INITIALIZATION_ERROR',
  IMPLEMENTATION_ERROR: 'IMPLEMENTATION_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  METHOD_NOT_IMPLEMENTED: 'METHOD_NOT_IMPLEMENTED',
  FEATURE_NOT_SUPPORTED: 'FEATURE_NOT_SUPPORTED',

  // 限制
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',

  // 品質評估
  FUNCTIONALITY_SCORE_TOO_LOW: 'FUNCTIONALITY_SCORE_TOO_LOW',

  // 並行與重試
  CONCURRENT_OPERATION_ERROR: 'CONCURRENT_OPERATION_ERROR',
  MAX_RETRIES_EXCEEDED: 'MAX_RETRIES_EXCEEDED',
  RETRY_CONFIG_NOT_SET: 'RETRY_CONFIG_NOT_SET',
  STILL_FAILING: 'STILL_FAILING',

  // 核心處理器
  CORE_PROCESS_ERROR: 'CORE_PROCESS_ERROR',
  CORE_HANDLER_ERROR: 'CORE_HANDLER_ERROR',
  // 命名風格不一致：CORE_EVENTBUS（無底線）為歷史遺留
  // 值不可更改以維持向後相容，未來新增統一使用 EVENT_BUS 風格
  // 注意：此代碼定義於 messaging.js，此處僅為交叉引用註解

  // Handler
  HANDLER_UI_SERVICE_UNAVAILABLE: 'HANDLER_UI_SERVICE_UNAVAILABLE',
  HANDLER_STORAGE_TEMPORARY_UNAVAILABLE: 'HANDLER_STORAGE_TEMPORARY_UNAVAILABLE',
  HANDLER_STORAGE_SERVICE_UNAVAILABLE: 'HANDLER_STORAGE_SERVICE_UNAVAILABLE',

  // Adapter
  ADAPTER_INITIALIZATION_ERROR: 'ADAPTER_INITIALIZATION_ERROR',
  ADAPTER_CONSTRUCTION_ERROR: 'ADAPTER_CONSTRUCTION_ERROR',

  // 系統延伸
  SYSTEM_OVERLOAD: 'SYSTEM_OVERLOAD',
  SYSTEM_INTERRUPTION: 'SYSTEM_INTERRUPTION',
  ENVIRONMENT_NOT_SETUP: 'ENVIRONMENT_NOT_SETUP',
  HEALTH_CHECK_ERROR: 'HEALTH_CHECK_ERROR',
  MODULE_COMPLETE_FAILURE: 'MODULE_COMPLETE_FAILURE',
  CIRCULAR_ERROR_DETECTED: 'CIRCULAR_ERROR_DETECTED',
  ERROR_RECOVERY_TEMPORARY_FAILURE: 'ERROR_RECOVERY_TEMPORARY_FAILURE',
  PRIORITY_CONFIG_NOT_SET: 'PRIORITY_CONFIG_NOT_SET',
  CASCADING_EXTRACTION_ERROR: 'CASCADING_EXTRACTION_ERROR',

  // 方法與實作
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',

  // 未知
  UNKNOWN_BUTTON: 'UNKNOWN_BUTTON',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
}

Object.freeze(SystemCodes)

module.exports = { SystemCodes }
