/**
 * UI 與通知顯示相關錯誤代碼
 *
 * 涵蓋 DOM 操作、渲染、Popup UI、通知系統（非匯出通知）等場景。
 */
const UiCodes = {
  DOM_ERROR: 'DOM_ERROR',
  RENDER_ERROR: 'RENDER_ERROR',
  UI_OPERATION_FAILED: 'UI_OPERATION_FAILED',
  UI_NOTIFICATION_DOM_ERROR: 'UI_NOTIFICATION_DOM_ERROR',
  POPUP_UI_UPDATE_ERROR: 'POPUP_UI_UPDATE_ERROR',
  POPUP_CONTEXT_NOT_FOUND: 'POPUP_CONTEXT_NOT_FOUND',
  CASCADING_UI_ERROR: 'CASCADING_UI_ERROR',
  NOTIFICATION_UI_SEND_ERROR: 'NOTIFICATION_UI_SEND_ERROR',
  NOTIFICATION_SOUND_PLAY_ERROR: 'NOTIFICATION_SOUND_PLAY_ERROR',
  NOTIFICATION_CLEAR_ERROR: 'NOTIFICATION_CLEAR_ERROR',
  NOTIFICATION_CLEANUP_EXPIRED_ERROR: 'NOTIFICATION_CLEANUP_EXPIRED_ERROR',
  NOTIFICATION_CHROME_SEND_ERROR: 'NOTIFICATION_CHROME_SEND_ERROR',
  NOTIFICATION_BROWSER_SEND_ERROR: 'NOTIFICATION_BROWSER_SEND_ERROR',
  NOTIFICATION_BATCH_CLEAR_ERROR: 'NOTIFICATION_BATCH_CLEAR_ERROR'
}

Object.freeze(UiCodes)

module.exports = { UiCodes }
