/**
 * 錯誤代碼常數定義 - 專家優化版
 *
 * 設計原則（基於 Linux/John Carmack 專家建議）：
 * - 精簡至 17 個核心代碼，避免過度分類
 * - 使用描述性名稱，涵蓋主要錯誤域
 * - 零運行時開銷，編譯時常數
 * - Chrome Extension ES modules 專用
 *
 * 使用方式：
 * const error = new Error(`${ErrorCodes.VALIDATION_ERROR}: Email is required`)
 * error.code = ErrorCodes.IMPLEMENTATION_ERROR
 * throw error
 *
 * 效能優化使用方式：
 * const error = new Error(message)
 * error.code = ErrorCodes.VALIDATION_ERROR
 * throw error
 */

/**
 * 系統錯誤代碼常數 - 核心代碼與擴展代碼
 * @readonly
 * @enum {string}
 */
const ErrorCodes = {
  // 驗證相關錯誤
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_INPUT_ERROR: 'INVALID_INPUT_ERROR',
  INVALID_DATA_FORMAT: 'INVALID_DATA_FORMAT',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',

  // 網路相關錯誤
  NETWORK_ERROR: 'NETWORK_ERROR',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',

  // 儲存相關錯誤
  STORAGE_ERROR: 'STORAGE_ERROR',

  // Readmoo 平台錯誤
  READMOO_ERROR: 'READMOO_ERROR',

  // Chrome Extension 錯誤
  CHROME_ERROR: 'CHROME_ERROR',

  // 書籍處理錯誤
  BOOK_ERROR: 'BOOK_ERROR',

  // DOM 操作錯誤
  DOM_ERROR: 'DOM_ERROR',

  // 檔案處理錯誤
  FILE_ERROR: 'FILE_ERROR',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  LARGE_FILES_DETECTED: 'LARGE_FILES_DETECTED',

  // 操作執行錯誤
  OPERATION_ERROR: 'OPERATION_ERROR',
  OPERATION_FAILED: 'OPERATION_FAILED',
  EXPORT_OPERATION_FAILED: 'EXPORT_OPERATION_FAILED',
  UI_OPERATION_FAILED: 'UI_OPERATION_FAILED',
  UNSUPPORTED_OPERATION: 'UNSUPPORTED_OPERATION',

  // 權限相關錯誤
  PERMISSION_ERROR: 'PERMISSION_ERROR',

  // 解析錯誤
  PARSE_ERROR: 'PARSE_ERROR',

  // 設定錯誤
  CONFIG_ERROR: 'CONFIG_ERROR',

  // 渲染錯誤
  RENDER_ERROR: 'RENDER_ERROR',

  // 效能錯誤
  PERFORMANCE_ERROR: 'PERFORMANCE_ERROR',
  PERFORMANCE_MEMORY_TOO_HIGH: 'PERFORMANCE_MEMORY_TOO_HIGH',
  PERFORMANCE_STARTUP_TOO_SLOW: 'PERFORMANCE_STARTUP_TOO_SLOW',

  // 資源相關錯誤
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_NOT_AVAILABLE: 'RESOURCE_NOT_AVAILABLE',
  RESOURCE_EXHAUSTED: 'RESOURCE_EXHAUSTED',
  MISSING_REQUIRED_DATA: 'MISSING_REQUIRED_DATA',

  // 系統相關錯誤
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  INITIALIZATION_ERROR: 'INITIALIZATION_ERROR',
  SERVICE_INITIALIZATION_ERROR: 'SERVICE_INITIALIZATION_ERROR',
  IMPLEMENTATION_ERROR: 'IMPLEMENTATION_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  FEATURE_NOT_SUPPORTED: 'FEATURE_NOT_SUPPORTED',

  // 事件總線錯誤
  EVENTBUS_ERROR: 'EVENTBUS_ERROR',
  EVENTBUS_REQUIRED: 'EVENTBUS_REQUIRED',

  // 限制相關錯誤
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',

  // 安全相關錯誤
  CODE_INJECTION_RISK: 'CODE_INJECTION_RISK',
  UNSAFE_CSP_EVAL: 'UNSAFE_CSP_EVAL',
  UNSAFE_CSP_INLINE: 'UNSAFE_CSP_INLINE',
  PRIVACY_UNDECLARED_DATA_COLLECTION: 'PRIVACY_UNDECLARED_DATA_COLLECTION',

  // Manifest 相關錯誤
  MANIFEST_MISSING_FIELDS: 'MANIFEST_MISSING_FIELDS',
  MANIFEST_VERSION_INVALID: 'MANIFEST_VERSION_INVALID',
  MISSING_EXTENSION_ICON: 'MISSING_EXTENSION_ICON',

  // 品質評估錯誤
  FUNCTIONALITY_SCORE_TOO_LOW: 'FUNCTIONALITY_SCORE_TOO_LOW',

  // 測試相關錯誤
  TEST_ERROR: 'TEST_ERROR',
  TEST_MOCK_ERROR: 'TEST_MOCK_ERROR',
  TEST_EXECUTION_ERROR: 'TEST_EXECUTION_ERROR',
  TEST_SIMULATOR_ERROR: 'TEST_SIMULATOR_ERROR',
  TEST_GENERATION_ERROR: 'TEST_GENERATION_ERROR',
  TEST_VALIDATION_ERROR: 'TEST_VALIDATION_ERROR',
  TEST_ENVIRONMENT_ERROR: 'TEST_ENVIRONMENT_ERROR',
  TEST_WORKFLOW_ERROR: 'TEST_WORKFLOW_ERROR',
  TEST_STORAGE_ERROR: 'TEST_STORAGE_ERROR',
  TEST_INITIALIZATION_ERROR: 'TEST_INITIALIZATION_ERROR',
  TESTING_INTEGRITY_ERROR: 'TESTING_INTEGRITY_ERROR',
  // 匯出相關錯誤
  EXPORT_FAILED: 'EXPORT_FAILED',
  EXPORT_CSV_FAILED: 'EXPORT_CSV_FAILED',
  EXPORT_CSV_SIMULATION_FAILED: 'EXPORT_CSV_SIMULATION_FAILED',
  EXPORT_DOWNLOAD_FAILED: 'EXPORT_DOWNLOAD_FAILED',
  EXPORT_DOWNLOAD_CONFIRMATION_ERROR: 'EXPORT_DOWNLOAD_CONFIRMATION_ERROR',
  EXPORT_URL_CREATION_FAILED: 'EXPORT_URL_CREATION_FAILED',
  EXPORT_MANAGER_INIT_FAILED: 'EXPORT_MANAGER_INIT_FAILED',
  EXPORT_BATCH_PARTIAL_FAILURE: 'EXPORT_BATCH_PARTIAL_FAILURE',
  EXPORT_TEMPORARY_FAILURE: 'EXPORT_TEMPORARY_FAILURE',
  EXPORT_LOCALIZATION_ERROR: 'EXPORT_LOCALIZATION_ERROR',
  EXPORT_LANGUAGE_SET_ERROR: 'EXPORT_LANGUAGE_SET_ERROR',
  EXPORT_DATETIME_FORMAT_ERROR: 'EXPORT_DATETIME_FORMAT_ERROR',
  EXPORT_ERROR_HUMANIZATION_ERROR: 'EXPORT_ERROR_HUMANIZATION_ERROR',
  EXPORT_BENCHMARK_COMPARISON_ERROR: 'EXPORT_BENCHMARK_COMPARISON_ERROR',
  EXPORT_USER_PREFERENCES_SAVE_ERROR: 'EXPORT_USER_PREFERENCES_SAVE_ERROR',
  EXPORT_USER_PREFERENCES_LOAD_ERROR: 'EXPORT_USER_PREFERENCES_LOAD_ERROR',
  EXPORT_USER_FEEDBACK_INIT_ERROR: 'EXPORT_USER_FEEDBACK_INIT_ERROR',
  EXPORT_PREFERENCES_VALIDATION_ERROR: 'EXPORT_PREFERENCES_VALIDATION_ERROR',
  EXPORT_PREFERENCES_RESET_ERROR: 'EXPORT_PREFERENCES_RESET_ERROR',
  EXPORT_PREFERENCES_MERGE_ERROR: 'EXPORT_PREFERENCES_MERGE_ERROR',
  EXPORT_STATISTICS_RANGE_ERROR: 'EXPORT_STATISTICS_RANGE_ERROR',
  EXPORT_STATISTICS_QUERY_ERROR: 'EXPORT_STATISTICS_QUERY_ERROR',
  EXPORT_HISTORY_SEARCH_ERROR: 'EXPORT_HISTORY_SEARCH_ERROR',
  EXPORT_HISTORY_QUERY_ERROR: 'EXPORT_HISTORY_QUERY_ERROR',
  EXPORT_HISTORY_EXPORT_ERROR: 'EXPORT_HISTORY_EXPORT_ERROR',
  EXPORT_PROGRESS_UPDATE_ERROR: 'EXPORT_PROGRESS_UPDATE_ERROR',
  EXPORT_PROGRESS_TRACKING_START_ERROR: 'EXPORT_PROGRESS_TRACKING_START_ERROR',
  EXPORT_PROGRESS_TRACKING_COMPLETE_ERROR: 'EXPORT_PROGRESS_TRACKING_COMPLETE_ERROR',
  EXPORT_PROGRESS_TRACKING_CANCEL_ERROR: 'EXPORT_PROGRESS_TRACKING_CANCEL_ERROR',
  EXPORT_PROGRESS_STATS_ERROR: 'EXPORT_PROGRESS_STATS_ERROR',
  EXPORT_PROGRESS_QUERY_ERROR: 'EXPORT_PROGRESS_QUERY_ERROR',
  EXPORT_PROGRESS_NOTIFIER_INIT_ERROR: 'EXPORT_PROGRESS_NOTIFIER_INIT_ERROR',
  EXPORT_PROGRESS_HISTORY_ERROR: 'EXPORT_PROGRESS_HISTORY_ERROR',
  EXPORT_PROGRESS_CLEANUP_ERROR: 'EXPORT_PROGRESS_CLEANUP_ERROR',
  EXPORT_PROGRESS_CALLBACK_REGISTRATION_ERROR: 'EXPORT_PROGRESS_CALLBACK_REGISTRATION_ERROR',

  // 通知相關錯誤
  EXPORT_NOTIFICATION_START_ERROR: 'EXPORT_NOTIFICATION_START_ERROR',
  EXPORT_NOTIFICATION_GROUP_ERROR: 'EXPORT_NOTIFICATION_GROUP_ERROR',
  EXPORT_NOTIFICATION_ERROR_ALERT: 'EXPORT_NOTIFICATION_ERROR_ALERT',
  EXPORT_NOTIFICATION_COMPLETE_ERROR: 'EXPORT_NOTIFICATION_COMPLETE_ERROR',
  EXPORT_NOTIFICATION_CLEANUP_ERROR: 'EXPORT_NOTIFICATION_CLEANUP_ERROR',
  EXPORT_NOTIFICATION_ADD_ERROR: 'EXPORT_NOTIFICATION_ADD_ERROR',
  NOTIFICATION_UI_SEND_ERROR: 'NOTIFICATION_UI_SEND_ERROR',
  NOTIFICATION_SOUND_PLAY_ERROR: 'NOTIFICATION_SOUND_PLAY_ERROR',
  NOTIFICATION_CLEAR_ERROR: 'NOTIFICATION_CLEAR_ERROR',
  NOTIFICATION_CLEANUP_EXPIRED_ERROR: 'NOTIFICATION_CLEANUP_EXPIRED_ERROR',
  NOTIFICATION_CHROME_SEND_ERROR: 'NOTIFICATION_CHROME_SEND_ERROR',
  NOTIFICATION_BROWSER_SEND_ERROR: 'NOTIFICATION_BROWSER_SEND_ERROR',
  NOTIFICATION_BATCH_CLEAR_ERROR: 'NOTIFICATION_BATCH_CLEAR_ERROR',

  // 網路延伸錯誤
  NETWORK_REQUEST_FAILED: 'NETWORK_REQUEST_FAILED',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  NETWORK_INTERRUPTION: 'NETWORK_INTERRUPTION',
  NETWORK_DISCONNECTED: 'NETWORK_DISCONNECTED',
  TEMPORARY_NETWORK_FAILURE: 'TEMPORARY_NETWORK_FAILURE',
  TEMPORARY_FAILURE: 'TEMPORARY_FAILURE',
  DNS_ERROR: 'DNS_ERROR',
  ENOTFOUND_ERROR: 'ENOTFOUND_ERROR',
  UNKNOWN_NETWORK_ERROR: 'UNKNOWN_NETWORK_ERROR',

  // 儲存延伸錯誤
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
  STORAGE_ADAPTER_FAILED: 'STORAGE_ADAPTER_FAILED',
  STORAGE_OPERATION_FAILED: 'STORAGE_OPERATION_FAILED',
  STORAGE_LOCAL_ERROR: 'STORAGE_LOCAL_ERROR',
  STORAGE_CORRUPTION_DETECTED: 'STORAGE_CORRUPTION_DETECTED',
  QUOTA_EXCEEDED_ERROR: 'QUOTA_EXCEEDED_ERROR',

  // 記憶體相關錯誤
  OUT_OF_MEMORY_ERROR: 'OUT_OF_MEMORY_ERROR',
  OUT_OF_MEMORY: 'OUT_OF_MEMORY',
  MEMORY_ERROR: 'MEMORY_ERROR',
  MEMORY_DETECTOR_ERROR: 'MEMORY_DETECTOR_ERROR',

  // 方法與實作錯誤
  METHOD_NOT_IMPLEMENTED: 'METHOD_NOT_IMPLEMENTED',
  INVALID_MOCK_IMPLEMENTATION: 'INVALID_MOCK_IMPLEMENTATION',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',

  // 並行與重試錯誤
  CONCURRENT_OPERATION_ERROR: 'CONCURRENT_OPERATION_ERROR',
  MAX_RETRIES_EXCEEDED: 'MAX_RETRIES_EXCEEDED',
  RETRY_CONFIG_NOT_SET: 'RETRY_CONFIG_NOT_SET',
  STILL_FAILING: 'STILL_FAILING',

  // 安全延伸錯誤
  SECURITY_ERROR: 'SECURITY_ERROR',
  CSP_VIOLATION: 'CSP_VIOLATION',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',

  // 訊息傳遞錯誤
  MESSAGE_DELIVERY_FAILED: 'MESSAGE_DELIVERY_FAILED',
  MESSAGE_TIMEOUT: 'MESSAGE_TIMEOUT',
  MULTICAST_TESTING_NOT_ENABLED: 'MULTICAST_TESTING_NOT_ENABLED',
  RECEIVER_UNAVAILABLE: 'RECEIVER_UNAVAILABLE',
  TARGET_CONTEXT_UNAVAILABLE: 'TARGET_CONTEXT_UNAVAILABLE',
  ROUTING_ANALYSIS_NOT_ENABLED: 'ROUTING_ANALYSIS_NOT_ENABLED',

  // Content Script 錯誤
  CONTENT_SCRIPT_ERROR: 'CONTENT_SCRIPT_ERROR',
  CONTENT_SCRIPT_TIMEOUT: 'CONTENT_SCRIPT_TIMEOUT',
  CONTENT_HANDLER_ERROR: 'CONTENT_HANDLER_ERROR',
  SCRIPT_LOADING_FAILED: 'SCRIPT_LOADING_FAILED',
  PAGE_NOT_READY: 'PAGE_NOT_READY',

  // Background Context 錯誤
  BACKGROUND_CONTEXT_NOT_INITIALIZED: 'BACKGROUND_CONTEXT_NOT_INITIALIZED',
  BACKGROUND_CONTEXT_NOT_AVAILABLE: 'BACKGROUND_CONTEXT_NOT_AVAILABLE',
  CONTEXT_NOT_FOUND: 'CONTEXT_NOT_FOUND',

  // UI 相關錯誤
  UI_NOTIFICATION_DOM_ERROR: 'UI_NOTIFICATION_DOM_ERROR',
  POPUP_UI_UPDATE_ERROR: 'POPUP_UI_UPDATE_ERROR',
  POPUP_CONTEXT_NOT_FOUND: 'POPUP_CONTEXT_NOT_FOUND',
  CASCADING_UI_ERROR: 'CASCADING_UI_ERROR',

  // 資料處理錯誤
  DATA_PARSING_FAILED: 'DATA_PARSING_FAILED',
  DATA_IMPORT_FORMAT_ERROR: 'DATA_IMPORT_FORMAT_ERROR',
  DATA_IMPORT_FIELD_ERROR: 'DATA_IMPORT_FIELD_ERROR',
  DATA_CORRUPTION_DETECTED: 'DATA_CORRUPTION_DETECTED',
  INVALID_FILE_FORMAT: 'INVALID_FILE_FORMAT',
  INVALID_IMPORT_FORMAT: 'INVALID_IMPORT_FORMAT',
  INVALID_COUNTER_VALUE: 'INVALID_COUNTER_VALUE',
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  INVALID_API_PATH: 'INVALID_API_PATH',
  URL_ANALYSIS_FAILURE: 'URL_ANALYSIS_FAILURE',

  // 核心處理器錯誤
  CORE_PROCESS_ERROR: 'CORE_PROCESS_ERROR',
  CORE_HANDLER_ERROR: 'CORE_HANDLER_ERROR',
  CORE_EVENTBUS_HANDLER_ERROR: 'CORE_EVENTBUS_HANDLER_ERROR',
  EVENT_BUS_TEMPORARY_FAILURE: 'EVENT_BUS_TEMPORARY_FAILURE',

  // Handler 錯誤
  HANDLER_UI_SERVICE_UNAVAILABLE: 'HANDLER_UI_SERVICE_UNAVAILABLE',
  HANDLER_STORAGE_TEMPORARY_UNAVAILABLE: 'HANDLER_STORAGE_TEMPORARY_UNAVAILABLE',
  HANDLER_STORAGE_SERVICE_UNAVAILABLE: 'HANDLER_STORAGE_SERVICE_UNAVAILABLE',

  // Adapter 錯誤
  ADAPTER_INITIALIZATION_ERROR: 'ADAPTER_INITIALIZATION_ERROR',
  ADAPTER_CONSTRUCTION_ERROR: 'ADAPTER_CONSTRUCTION_ERROR',

  // 系統延伸錯誤
  SYSTEM_OVERLOAD: 'SYSTEM_OVERLOAD',
  SYSTEM_INTERRUPTION: 'SYSTEM_INTERRUPTION',
  ENVIRONMENT_NOT_SETUP: 'ENVIRONMENT_NOT_SETUP',
  HEALTH_CHECK_ERROR: 'HEALTH_CHECK_ERROR',
  MODULE_COMPLETE_FAILURE: 'MODULE_COMPLETE_FAILURE',
  CIRCULAR_ERROR_DETECTED: 'CIRCULAR_ERROR_DETECTED',
  ERROR_SIMULATION: 'ERROR_SIMULATION',
  ERROR_INJECTION_NOT_ENABLED: 'ERROR_INJECTION_NOT_ENABLED',
  ERROR_RECOVERY_TEMPORARY_FAILURE: 'ERROR_RECOVERY_TEMPORARY_FAILURE',
  RANDOM_FAILURE: 'RANDOM_FAILURE',
  PRIORITY_CONFIG_NOT_SET: 'PRIORITY_CONFIG_NOT_SET',
  CASCADING_EXTRACTION_ERROR: 'CASCADING_EXTRACTION_ERROR',

  // Chrome Extension 延伸錯誤
  EXTENSION_RUNTIME_ERROR: 'EXTENSION_RUNTIME_ERROR',
  UNKNOWN_BUTTON: 'UNKNOWN_BUTTON',

  // E2E 測試錯誤
  E2E_STORAGE_QUOTA_EXCEEDED: 'E2E_STORAGE_QUOTA_EXCEEDED',
  E2E_PERSISTENT_ERROR: 'E2E_PERSISTENT_ERROR',
  E2E_CONTEXT_DISCONNECTED: 'E2E_CONTEXT_DISCONNECTED',
  E2E_CONTENT_SCRIPT_ERROR: 'E2E_CONTENT_SCRIPT_ERROR',
  E2E_CONFLICT_RESOLUTION_UI_TIMEOUT: 'E2E_CONFLICT_RESOLUTION_UI_TIMEOUT',

  // 未知錯誤
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
}

// 凍結物件以防止意外修改
Object.freeze(ErrorCodes)

/**
 * 預編譯常用錯誤模式（John Carmack 效能優化建議）
 * 避免熱路徑中的字串拼接成本
 */
const CommonErrors = {
  EMAIL_REQUIRED: Object.freeze(createError(ErrorCodes.VALIDATION_ERROR, 'Email is required')),
  TITLE_REQUIRED: Object.freeze(createError(ErrorCodes.VALIDATION_ERROR, 'Title is required')),
  NETWORK_TIMEOUT: Object.freeze(createError(ErrorCodes.TIMEOUT_ERROR, 'Network request timeout')),
  READMOO_LOGIN_FAILED: Object.freeze(createError(ErrorCodes.READMOO_ERROR, 'Login to Readmoo failed')),
  BOOK_EXTRACTION_FAILED: Object.freeze(createError(ErrorCodes.BOOK_ERROR, 'Book data extraction failed'))
}

/**
 * 效能優化的錯誤建立函數
 * @param {string} code - 錯誤代碼
 * @param {string} message - 錯誤訊息
 * @returns {Error} 帶有 code 屬性的 Error 物件
 */
function createError (code, message) {
  const error = new Error(message)
  error.code = code
  return error
}

// CommonJS 支援
module.exports = {
  ErrorCodes,
  CommonErrors,
  createError
}
