/**
 * 錯誤類型枚舉
 * 
 * 定義所有錯誤的標準類型分類，確保系統中錯誤類型的一致性
 * 對應規劃文件中的錯誤分類架構
 */

const ErrorTypes = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  STORAGE_ERROR: 'STORAGE_ERROR',
  BUSINESS_ERROR: 'BUSINESS_ERROR',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  PERMISSION_ERROR: 'PERMISSION_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  
  // Chrome Extension 特定錯誤
  EXTENSION_ERROR: 'EXTENSION_ERROR',
  CONTENT_SCRIPT_ERROR: 'CONTENT_SCRIPT_ERROR',
  BACKGROUND_SCRIPT_ERROR: 'BACKGROUND_SCRIPT_ERROR',
  POPUP_ERROR: 'POPUP_ERROR',
  
  // 書籍處理特定錯誤
  BOOK_EXTRACTION_ERROR: 'BOOK_EXTRACTION_ERROR',
  BOOK_VALIDATION_ERROR: 'BOOK_VALIDATION_ERROR',
  BOOK_SYNC_ERROR: 'BOOK_SYNC_ERROR',
  
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
})

/**
 * 錯誤嚴重程度枚舉
 */
const ErrorSeverity = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM', 
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
})


module.exports = {
  ErrorTypes,
  ErrorSeverity
}