/**
 * Design System CSS 產生器 snapshot test（0.19.1-W2-001.1）
 *
 * 目的：驗證 scripts/generate-design-system-css.js 產出的 design-system.css
 *   含預期 :root 關鍵 token 且格式正確。token 增減（新增 / 移除 / 改值）會
 *   觸發本測試失敗，作為「3 個 .js 來源 → CSS 產物」橋接的回歸防線。
 *
 * 為何斷言「產生器輸出」而非「磁碟上的 design-system.css」：
 *   產生器以 buildCss() 為單一來源，build.js 與 validate:design-system 皆呼叫
 *   同一函式。直接斷言 buildCss() 輸出即驗證了產物內容；磁碟檔的一致性另由
 *   npm run validate:design-system（git diff --exit-code）於 CI 把關。
 *
 * @see scripts/generate-design-system-css.js
 * @see docs/work-logs/.../0.19.1-W2-001.md Solution 第 1 節
 */

const { buildCss, camelToKebab } = require('../../scripts/generate-design-system-css.js')
const { STATUS_COLORS } = require('../../src/core/design-system/colors.js')
const { SHADOW_COLORS, OVERLAY_COLORS } = require('../../src/core/design-system/shadows.js')

describe('design-system.css 產生器', () => {
  let css

  beforeAll(() => {
    css = buildCss()
  })

  describe('檔案結構', () => {
    test('檔頭含 AUTO-GENERATED 註解（禁手改宣告）', () => {
      expect(css).toContain('/* AUTO-GENERATED by scripts/generate-design-system-css.js — DO NOT EDIT */')
    })

    test('含單一 :root 區塊起訖', () => {
      expect(css).toContain(':root {')
      expect(css.trim().endsWith('}')).toBe(true)
      // 僅一個 :root 宣告
      expect(css.match(/:root\s*\{/g)).toHaveLength(1)
    })

    test('每個變數宣告皆為 `  --name: value;` 格式', () => {
      const varLines = css.split('\n').filter((line) => line.trim().startsWith('--'))
      expect(varLines.length).toBeGreaterThan(0)
      varLines.forEach((line) => {
        expect(line).toMatch(/^ {2}--[a-z0-9-]+: .+;$/)
      })
    })
  })

  describe('Colors（Section 2）關鍵 token', () => {
    test('--color-primary 為 Material Blue #2196F3', () => {
      expect(css).toContain('--color-primary: #2196F3;')
    })

    test('camelCase key 轉 kebab-case（primaryLightest → --color-primary-lightest）', () => {
      expect(css).toContain('--color-primary-lightest: #E3F2FD;')
    })

    test('含背景 / 表面 / 錯誤 / 邊框等核心色', () => {
      expect(css).toContain('--color-background: #FAFAFA;')
      expect(css).toContain('--color-surface: #FFFFFF;')
      expect(css).toContain('--color-error: #F44336;')
      expect(css).toContain('--color-border: #E0E0E0;')
    })
  })

  describe('Status Badge Colors（Section 3，D3 修正後）', () => {
    test('unread 為深字淺底（#546E7A / #ECEFF1，WCAG AA 4.68:1）', () => {
      expect(css).toContain('--status-unread-fg: #546E7A;')
      expect(css).toContain('--status-unread-bg: #ECEFF1;')
    })

    test('6 個狀態各自產出 fg / bg 共 12 個變數', () => {
      const statusVarCount = (css.match(/--status-[a-z]+-(fg|bg):/g) || []).length
      expect(statusVarCount).toBe(12)
    })

    test('產出值與 colors.js STATUS_COLORS 為單一來源（無漂移）', () => {
      Object.keys(STATUS_COLORS).forEach((status) => {
        const { fg, bg } = STATUS_COLORS[status]
        const kebab = camelToKebab(status)
        expect(css).toContain(`--status-${kebab}-fg: ${fg};`)
        expect(css).toContain(`--status-${kebab}-bg: ${bg};`)
      })
    })

    test('不含舊 alpha 背景或 rgba（D3 改不透明色）', () => {
      const statusLines = css.split('\n').filter((line) => line.includes('--status-'))
      statusLines.forEach((line) => {
        expect(line).not.toMatch(/rgba/)
      })
    })
  })

  describe('Spacing（Section 5）與 Border Radius（Section 6）', () => {
    test('spacing 數字轉 px（md → 16px）', () => {
      expect(css).toContain('--spacing-md: 16px;')
      expect(css).toContain('--spacing-xxs: 2px;')
    })

    test('radius 數字轉 px（md → 12px）', () => {
      expect(css).toContain('--radius-md: 12px;')
    })
  })

  describe('Typography（Section 7）', () => {
    test('font-family 保留字串原值', () => {
      expect(css).toContain("--font-family: 'PingFang SC', 'Microsoft YaHei', sans-serif;")
    })

    test('font-size 數字轉 px（bodyMedium → --font-size-body-medium: 14px）', () => {
      expect(css).toContain('--font-size-body-medium: 14px;')
    })

    test('font-weight 保留無單位數字（semiBold → --font-weight-semi-bold: 600）', () => {
      expect(css).toContain('--font-weight-semi-bold: 600;')
      expect(css).toContain('--font-weight-bold: 700;')
    })
  })

  describe('Shadows & Overlay（Section 8）', () => {
    test('陰影顏色兩級（sm 0.1 輕陰影 / md 0.25 中陰影）', () => {
      expect(css).toContain('--shadow-color-sm: rgba(0, 0, 0, 0.1);')
      expect(css).toContain('--shadow-color-md: rgba(0, 0, 0, 0.25);')
    })

    test('overlay scrim（modal backdrop 半透明黑底 0.5）', () => {
      expect(css).toContain('--overlay-scrim: rgba(0, 0, 0, 0.5);')
    })

    test('產出值與 shadows.js SHADOW_COLORS / OVERLAY_COLORS 為單一來源（無漂移）', () => {
      Object.keys(SHADOW_COLORS).forEach((key) => {
        expect(css).toContain(`--shadow-color-${camelToKebab(key)}: ${SHADOW_COLORS[key]};`)
      })
      Object.keys(OVERLAY_COLORS).forEach((key) => {
        expect(css).toContain(`--overlay-${camelToKebab(key)}: ${OVERLAY_COLORS[key]};`)
      })
    })
  })

  describe('camelToKebab 工具函式', () => {
    test('多種 camelCase 輸入', () => {
      expect(camelToKebab('primaryLightest')).toBe('primary-lightest')
      expect(camelToKebab('bodyLarge')).toBe('body-large')
      expect(camelToKebab('semiBold')).toBe('semi-bold')
      expect(camelToKebab('xxs')).toBe('xxs')
      expect(camelToKebab('headline3')).toBe('headline3')
    })
  })
})
